### ISSUE TITLE
用了链接后是服务器关闭或者链接错误

### ISSUE THREAD

**Issue by Kam1GJJ** [ikexing-cn/bilibili-live-stream#1]
请输入BiliBili直播间房间号：
35
请选择清晰度：
0 原画
1 蓝光
2 超清
3 高清
0
视频地址如下(包含全部线路)：
https://d1--cn-gotcha104.bilivideo.com/live-bvc/165348/live_474595627_50840492.m3u8?cdn=cn-gotcha04&expires=1652245757&len=0&oi=0x2408820c4e0bb0305818bb1998bbed91&pt=h5&qn=10000&trid=1003b4bfbef54c254a85af0947cb5a064576&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=4f526fe1265058b99e7512b735356488&ptype=0&src=57601&sl=6&source=one&sk=82cd5f378e58b2360fe47b00aad213e0&order=1
是否需要输出到文件？(输入任意键执行，输入n取消)

**Comment by Kam1GJJ** [comment]
就是35房间号，用了出来的线路是错误

**Comment by ikexing-cn** [comment]
![图片](https://user-images.githubusercontent.com/75018198/167767785-def6312c-cb59-41ed-ab64-3b22b14bd6d3.png)

----------------

我不太理解 我这边是正常的

**Comment by Kam1GJJ** [comment]
为啥我这就出来一个流你那有四个:p

**Comment by ikexing-cn** [comment]
![图片](https://user-images.githubusercontent.com/75018198/167767892-22e91901-fa1f-452a-b994-5ff5e1c2d24d.png)

你可以随便按个键输出到文件里，然后会在相同的目录生成一个urls.txt 全部复制然后potplayer ctrl+u就行了，四个流是包括b站给的主线路+三个备用线路，我猜测很可能是你手动复制控制台的有编码错误什么的。

-------

你给的线路确实用不了，应该是你复制有误我猜测

**Comment by Kam1GJJ** [comment]
好的我再去试试

**Comment by Kam1GJJ** [comment]
不行。我这里输入和你一样的直播间号之后，为啥出来的流和你的不一样，出来的那个是不行的

**Comment by ikexing-cn** [comment]
你试试把35改成21622811看看？

**Comment by Kam1GJJ** [comment]
emm一样是d1开头的https://d1--cn-gotcha104.bilivideo.com/live-bvc/371578/live_474595627_50840492.m3u8?cdn=cn-gotcha04&expires=1652246788&len=0&oi=0x2408820c4e0bb0305818bb1998bbed91&pt=h5&qn=10000&trid=10030687632fa1c142cf9fdcb01103db099e&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=5e3213e7051cdcccb7c6f4511be5fb1d&ptype=0&src=57601&sl=5&source=one&sk=82cd5f378e58b2360fe47b00aad213e0&order=1
不知道为啥

**Comment by Kam1GJJ** [comment]
是少下了什么么

**Comment by ikexing-cn** [comment]
https://cn-gdgz-fx-live-04.bilivideo.com/live-bvc/385218/live_474595627_50840492_2500.m3u8?cdn=cn-gotcha01&expires=1652246791&len=0&oi=3070644672&pt=h5&qn=250&trid=1003af14eaf068474d59b8b2a85387dfc331&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=300a9bf05ee42c805b61cb8cb2b8b3ae&ptype=0&src=57601&sl=5&source=one&sid=42416&sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44&order=1

试试看这个链接可以吗

**Comment by Kam1GJJ** [comment]
可以

**Comment by Kam1GJJ** [comment]
我里面打出来的就不行==

**Comment by ikexing-cn** [comment]
可能是地区的原因…我这边在广州拿到的地址是可用，这个我得想想有什么新的解决办法

**Comment by Kam1GJJ** [comment]
emm好吧

**Comment by ikexing-cn** [comment]
试试用浏览器打开这个地址：https://api.live.bilibili.com/xlive/web-room/v1/playUrl/playUrl?&cid=21622811&platform=h5&ts=1643958874

然后给我看看信息

https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?&protocol=0,1&format=0,1,2&codec=0,1&room_id=21622811

第二个如果可以也试试

不要直接打开，复制到浏览器里面用

**Comment by Kam1GJJ** [comment]
第一个{"code":0,"message":"0","ttl":1,"data":{"current_qn":250,"quality_description":[{"qn":10000,"desc":"原画"},{"qn":400,"desc":"蓝光"},{"qn":250,"desc":"超清"},{"qn":150,"desc":"高清"}],"durl":[{"url":"https://d1--cn-gotcha104.bilivideo.com/live-bvc/247754/live_474595627_50840492_2500.m3u8?cdn=cn-gotcha04\u0026expires=1652247151\u0026len=0\u0026oi=0x2408820c4e0bb0305818bb1998bbed91\u0026pt=h5\u0026qn=250\u0026trid=100398ecb99f36e049beaa9a85bb9d1cf009\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026sign=4affde4fdd7dfa8b05c4ca533e272119\u0026ptype=0\u0026src=57601\u0026sl=4\u0026source=one\u0026sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026order=1","length":0,"order":1,"stream_type":0,"ptag":0,"p2p_type":0}],"is_dash_auto":false}}

**Comment by Kam1GJJ** [comment]
第二个{"code":0,"message":"0","ttl":1,"data":{"room_id":21622811,"short_id":35,"uid":474595627,"is_hidden":false,"is_locked":false,"is_portrait":false,"live_status":1,"hidden_till":0,"lock_till":0,"encrypted":false,"pwd_verified":true,"live_time":1650883072,"room_shield":1,"all_special_types":[19],"playurl_info":{"conf_json":"{\"cdn_rate\":10000,\"report_interval_sec\":150}","playurl":{"cid":21622811,"g_qn_desc":[{"qn":30000,"desc":"杜比","hdr_desc":""},{"qn":20000,"desc":"4K","hdr_desc":""},{"qn":10000,"desc":"原画","hdr_desc":""},{"qn":400,"desc":"蓝光","hdr_desc":"HDR"},{"qn":250,"desc":"超清","hdr_desc":"HDR"},{"qn":150,"desc":"高清","hdr_desc":""},{"qn":80,"desc":"流畅","hdr_desc":""}],"stream":[{"protocol_name":"http_stream","format":[{"format_name":"flv","codec":[{"codec_name":"avc","current_qn":400,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/872748/live_474595627_50840492_4000.flv?expires=1652247329\u0026len=0\u0026oi=0x2408820c4e0bb0305818bb1998bbed91\u0026pt=web\u0026qn=0\u0026trid=10009041fce34ca14aff8aefb83d4a423093\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://cn-hbcd-cu-02-08.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=e87877fb9c9b1ec0562f217d9cad7053\u0026sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=jd\u0026pp=rtmp\u0026sid=cn-hbcd-cu-02-08\u0026chash=1\u0026sche=ban\u0026source=onetier\u0026order=1\u0026site=3d745c99184b57ca5120de94027bfb21","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0},{"codec_name":"hevc","current_qn":250,"accept_qn":[10000,250],"base_url":"/live-bvc/872748/live_474595627_50840492_minihevc.flv?expires=1652247329\u0026len=0\u0026oi=0x2408820c4e0bb0305818bb1998bbed91\u0026pt=web\u0026qn=0\u0026trid=10009041fce34ca14aff8aefb83d4a423093\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://cn-hbcd-cu-02-07.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=b37b34eacc4ba3bf01d310b93836f54a\u0026sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=jd\u0026pp=rtmp\u0026sid=cn-hbcd-cu-02-07\u0026chash=1\u0026sche=ban\u0026source=onetier\u0026order=1\u0026site=3d745c99184b57ca5120de94027bfb21","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0}]}]},{"protocol_name":"http_hls","format":[{"format_name":"ts","codec":[{"codec_name":"avc","current_qn":400,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/872748/live_474595627_50840492_4000.m3u8?expires=1652247329\u0026len=0\u0026oi=0x2408820c4e0bb0305818bb1998bbed91\u0026pt=web\u0026qn=0\u0026trid=10039041fce34ca14aff8aefb83d4a423093\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://cn-hbcd-cu-02-07.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=5bf0434425961065504d2e9dd3fbcc51\u0026sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=jd\u0026pp=rtmp\u0026sid=cn-hbcd-cu-02-07\u0026chash=0\u0026sche=ban\u0026source=onetier\u0026order=1\u0026site=3d745c99184b57ca5120de94027bfb21","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0}]},{"format_name":"fmp4","codec":[{"codec_name":"avc","current_qn":400,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/872748/live_474595627_50840492_4000/index.m3u8?expires=1652247329\u0026len=0\u0026oi=0x2408820c4e0bb0305818bb1998bbed91\u0026pt=web\u0026qn=0\u0026trid=10079041fce34ca14aff8aefb83d4a423093\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://d1--cn-gotcha208.bilivideo.com","extra":"\u0026cdn=cn-gotcha208\u0026sign=3ecc719d9ad12ca5cb1c2cf6bf132406\u0026sk=c9c6154426932efa80d25af02e87a3bd\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=jd\u0026pp=rtmp\u0026source=onetier\u0026order=1\u0026site=3d745c99184b57ca5120de94027bfb21","stream_ttl":3600},{"host":"https://cn-hbcd-cu-02-07.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=03e57025c704542f942b9d359fe7f5d7\u0026sk=c9c6154426932efa80d25af02e87a3bd\u0026flvsk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=jd\u0026pp=rtmp\u0026sid=cn-hbcd-cu-02-07\u0026chash=0\u0026sche=ban\u0026source=onetier\u0026order=2\u0026site=3d745c99184b57ca5120de94027bfb21","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0},{"codec_name":"hevc","current_qn":250,"accept_qn":[10000,250],"base_url":"/live-bvc/872748/live_474595627_50840492_minihevc/index.m3u8?expires=1652247329\u0026len=0\u0026oi=0x2408820c4e0bb0305818bb1998bbed91\u0026pt=web\u0026qn=0\u0026trid=10079041fce34ca14aff8aefb83d4a423093\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://d1--cn-gotcha208.bilivideo.com","extra":"\u0026cdn=cn-gotcha208\u0026sign=e175cf1876287afe68c72275a52aee50\u0026sk=c9c6154426932efa80d25af02e87a3bd\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=jd\u0026pp=rtmp\u0026source=onetier\u0026order=1\u0026site=3d745c99184b57ca5120de94027bfb21","stream_ttl":3600},{"host":"https://cn-hbcd-cu-02-07.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=86e174cb9ae262c3b3b435e48bc6be80\u0026sk=c9c6154426932efa80d25af02e87a3bd\u0026flvsk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=jd\u0026pp=rtmp\u0026sid=cn-hbcd-cu-02-07\u0026chash=0\u0026sche=ban\u0026source=onetier\u0026order=2\u0026site=3d745c99184b57ca5120de94027bfb21","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0}]}]}],"p2p_data":{"p2p":true,"p2p_type":1,"m_p2p":false,"m_servers":null},"dolby_qn":null}}}}

**Comment by ikexing-cn** [comment]
看来v1api你用不了 v2api没问题 等我下午肝出来一个v2 api的吧（

**Comment by Kam1GJJ** [comment]
牛的，辛苦大佬了

**Comment by ikexing-cn** [comment]
写完了（
但是不知道为啥v2只有一条链接，我也不知道具体api的用法，不过总比一条都用不了好（

https://github.com/ikexing-cn/bilibili-live-stream/releases

下0.02版试一试

**Comment by ikexing-cn** [comment]
不对……清晰度代码写错了，直接下0.0.3版测试吧

**Comment by Kam1GJJ** [comment]
ok试过了可以用，感谢好兄弟
