### ISSUE TITLE
软件导出的链接无法播放

### ISSUE THREAD

**Issue by Uob1to** [ikexing-cn/bilibili-live-stream#2]
![image](https://user-images.githubusercontent.com/100673201/167810685-60f1d3c0-6c63-45a2-9f40-b7e37f1a7b68.png)

**Comment by Uob1to** [comment]
> ![image](https://user-images.githubusercontent.com/100673201/167810685-60f1d3c0-6c63-45a2-9f40-b7e37f1a7b68.png)

**Comment by ikexing-cn** [comment]
软件版本？还有链接有v1和v2都试过吗，操作的流程是什么样的

**Comment by Uob1to** [comment]
但是你在前一个issue给的链接能打开
![image](https://user-images.githubusercontent.com/100673201/167811058-0ffd7d31-55b5-47a1-8a43-d37fc3b32633.png)

**Comment by ikexing-cn** [comment]
请回答我的问题，不要扯前一个了……

**Comment by Uob1to** [comment]
> 软件版本？还有链接有v1和v2都试过吗，操作的流程是什么样的

都是按照你说的操作，v1，v2都试过，房间号全输进去和输35都不行

**Comment by ikexing-cn** [comment]
整个软件的截图发过来，包括链接的截图

**Comment by Uob1to** [comment]
> 软件版本？还有链接有v1和v2都试过吗，操作的流程是什么样的

![image](https://user-images.githubusercontent.com/100673201/167811477-66693d11-0636-4f33-a0cb-3ed368632f51.png)
在这两个链接打开都是这样的
![image](https://user-images.githubusercontent.com/100673201/167811572-4e3805a5-ee33-4890-80ed-af19c2fc31c0.png)

**Comment by ikexing-cn** [comment]
说过了，不要直接打开，复制到浏览器的地址栏里面……

**Comment by Uob1to** [comment]
> 整个软件的截图发过来，包括链接的截图

![image](https://user-images.githubusercontent.com/100673201/167811760-1226bf4d-b856-4393-8f5b-42add9d7dc53.png)
https://d1--cn-gotcha104.bilivideo.com/live-bvc/361952/live_474595627_50840492_4000.m3u8?cdn=cn-gotcha04&expires=1652263170&len=0&oi=720755942&pt=h5&qn=400&trid=10035cdfcdd397574e16894df769b48700d7&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=160b2fccbdb2ceffc93ed077b5a5633b&ptype=0&src=57601&sl=3&source=one&sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44&order=1
![image](https://user-images.githubusercontent.com/100673201/167811900-38e49770-e1cc-433c-b7c0-001f7f3342e2.png)

**Comment by ikexing-cn** [comment]
打开给我信息啊哥

选原画试试。

**Comment by Uob1to** [comment]
> 打开给我信息啊哥

不好意思
![image](https://user-images.githubusercontent.com/100673201/167812339-468aa6c0-9d41-4e42-aaa3-ca92def048c1.png)

{"code":0,"message":"0","ttl":1,"data":{"current_qn":250,"quality_description":[{"qn":10000,"desc":"原画"},{"qn":400,"desc":"蓝光"},{"qn":250,"desc":"超清"},{"qn":150,"desc":"高清"}],"durl":[{"url":"https://d1--cn-gotcha104.bilivideo.com/live-bvc/481308/live_474595627_50840492_2500.m3u8?cdn=cn-gotcha04

**Comment by ikexing-cn** [comment]
你这信息很明显不全 另外这个不是PotPlayer地址！！！
我只是想要你这个信息定位问题，还有v2的地址也发一下，既然你可以正常上github
合理运用gist.github.com

**Comment by Uob1to** [comment]
> 打开给我信息啊哥

第一个链接

**Comment by ikexing-cn** [comment]
你给我有什么用啊 你要自己打开我才能定位啊 这个是根据网络拿到的数据 你都看上个issue了 不能看看别人是怎么给我定位的信息吗 血压上来了

**Comment by Uob1to** [comment]
> 

哎呀点错了关闭
我是个小白

**Comment by Uob1to** [comment]
> 你给我有什么用啊 你要自己打开我才能定位啊 这个是根据网络拿到的数据 你都看上个issue了 不能看看别人是怎么给我定位的信息吗 血压上来了
第一个的
{"code":0,"message":"0","ttl":1,"data":{"current_qn":250,"quality_description":[{"qn":10000,"desc":"原画"},{"qn":400,"desc":"蓝光"},{"qn":250,"desc":"超清"},{"qn":150,"desc":"高清"}],"durl":[{"url":"https://d1--cn-gotcha104.bilivideo.com/live-bvc/481308/live_474595627_50840492_2500.m3u8?cdn=cn-gotcha04\u0026expires=1652263246\u0026len=0\u0026oi=720755942\u0026pt=h5\u0026qn=250\u0026trid=1003919cedd30fc94e29a0347adc3f8e83f0\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026sign=ac406731570d987d343bf7da00bbed43\u0026ptype=0\u0026src=57601\u0026sl=3\u0026source=one\u0026sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026order=1","length":0,"order":1,"stream_type":0,"ptag":0,"p2p_type":0}],"is_dash_auto":false}}

**Comment by Uob1to** [comment]
> 你给我有什么用啊 你要自己打开我才能定位啊 这个是根据网络拿到的数据 你都看上个issue了 不能看看别人是怎么给我定位的信息吗 血压上来了

第二个的
{"code":0,"message":"0","ttl":1,"data":{"room_id":21622811,"short_id":35,"uid":474595627,"is_hidden":false,"is_locked":false,"is_portrait":false,"live_status":1,"hidden_till":0,"lock_till":0,"encrypted":false,"pwd_verified":true,"live_time":1650883072,"room_shield":1,"all_special_types":[19],"playurl_info":{"conf_json":"{\"cdn_rate\":10000,\"report_interval_sec\":150}","playurl":{"cid":21622811,"g_qn_desc":[{"qn":30000,"desc":"杜比","hdr_desc":""},{"qn":20000,"desc":"4K","hdr_desc":""},{"qn":10000,"desc":"原画","hdr_desc":""},{"qn":400,"desc":"蓝光","hdr_desc":"HDR"},{"qn":250,"desc":"超清","hdr_desc":"HDR"},{"qn":150,"desc":"高清","hdr_desc":""},{"qn":80,"desc":"流畅","hdr_desc":""}],"stream":[{"protocol_name":"http_stream","format":[{"format_name":"flv","codec":[{"codec_name":"avc","current_qn":400,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/198125/live_474595627_50840492_4000.flv?expires=1652263636\u0026len=0\u0026oi=720755942\u0026pt=web\u0026qn=0\u0026trid=10008d1aa20ef07b46a28b36b5f416e53ba1\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://cn-hbyc-ct-02-27.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=0accc8509ebb38fc8f0f5f3b5471390f\u0026sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=ylf\u0026pp=rtmp\u0026sid=cn-hbyc-ct-02-27\u0026chash=1\u0026sche=ban\u0026source=onetier\u0026order=1\u0026site=9c795ee537775d97ff3c5d0f652a7b9f","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0},{"codec_name":"hevc","current_qn":250,"accept_qn":[10000,250],"base_url":"/live-bvc/198125/live_474595627_50840492_minihevc.flv?expires=1652263636\u0026len=0\u0026oi=720755942\u0026pt=web\u0026qn=0\u0026trid=10008d1aa20ef07b46a28b36b5f416e53ba1\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://cn-hbyc-ct-02-27.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=c2d9654c33b3dd637e8f64c73a18ad19\u0026sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=ylf\u0026pp=rtmp\u0026sid=cn-hbyc-ct-02-27\u0026chash=1\u0026sche=ban\u0026source=onetier\u0026order=1\u0026site=9c795ee537775d97ff3c5d0f652a7b9f","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0}]}]},{"protocol_name":"http_hls","format":[{"format_name":"ts","codec":[{"codec_name":"avc","current_qn":400,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/198125/live_474595627_50840492_4000.m3u8?expires=1652263636\u0026len=0\u0026oi=720755942\u0026pt=web\u0026qn=0\u0026trid=10038d1aa20ef07b46a28b36b5f416e53ba1\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://cn-hbyc-ct-02-27.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=9193fd0212417e8776858f3356e574e8\u0026sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=ylf\u0026pp=rtmp\u0026sid=cn-hbyc-ct-02-27\u0026chash=0\u0026sche=ban\u0026source=onetier\u0026order=1\u0026site=9c795ee537775d97ff3c5d0f652a7b9f","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0}]},{"format_name":"fmp4","codec":[{"codec_name":"avc","current_qn":400,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/198125/live_474595627_50840492_4000/index.m3u8?expires=1652263636\u0026len=0\u0026oi=720755942\u0026pt=web\u0026qn=0\u0026trid=10078d1aa20ef07b46a28b36b5f416e53ba1\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://cn-hbyc-ct-02-27.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=dd28607d38a9f20652aefb122d770e96\u0026sk=c9c6154426932efa80d25af02e87a3bd\u0026flvsk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=ylf\u0026pp=rtmp\u0026sid=cn-hbyc-ct-02-27\u0026chash=0\u0026sche=ban\u0026source=onetier\u0026order=1\u0026site=9c795ee537775d97ff3c5d0f652a7b9f","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0},{"codec_name":"hevc","current_qn":250,"accept_qn":[10000,250],"base_url":"/live-bvc/198125/live_474595627_50840492_minihevc/index.m3u8?expires=1652263636\u0026len=0\u0026oi=720755942\u0026pt=web\u0026qn=0\u0026trid=10078d1aa20ef07b46a28b36b5f416e53ba1\u0026sigparams=cdn,expires,len,oi,pt,qn,trid","url_info":[{"host":"https://cn-hbyc-ct-02-27.bilivideo.com","extra":"\u0026cdn=cn-gotcha01\u0026sign=2df137cca2da1ddf5cb30afe4e63d60c\u0026sk=c9c6154426932efa80d25af02e87a3bd\u0026flvsk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44\u0026p2p_type=1\u0026src=57601\u0026sl=4\u0026free_type=0\u0026flowtype=1\u0026machinezone=ylf\u0026pp=rtmp\u0026sid=cn-hbyc-ct-02-27\u0026chash=0\u0026sche=ban\u0026source=onetier\u0026order=1\u0026site=9c795ee537775d97ff3c5d0f652a7b9f","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0}]}]}],"p2p_data":{"p2p":true,"p2p_type":1,"m_p2p":false,"m_servers":null},"dolby_qn":null}}}}

**Comment by ikexing-cn** [comment]
用v2API 
![{IWA78WCW9SC35AF~I$HR{M](https://user-images.githubusercontent.com/75018198/167813736-d8cdb86f-2cc0-475d-8e1a-26f4047f7c1c.png)

你给的信息中提供的地址完全能用，请检查自己有没有用错

**Comment by ikexing-cn** [comment]
![图片](https://user-images.githubusercontent.com/75018198/167814007-6d58fa8b-2ee1-4292-90d1-2e6a24e9db7e.png)
操作方式，本issue不再回复。
