### ISSUE TITLE
获取的流无效

### ISSUE THREAD

**Issue by YuHuai-Golden** [ikexing-cn/bilibili-live-stream#4]
感谢您的工具，但是我今天第一次使用，在获取33直播间的流是失败的；获取35直播间的四个流按您的说明放到potplayer中均无法打开
截图没有办法上传，但是pot中确实点击后显示文件无法播放
（另外我下载的是只下载了exe，zip和另一个文件我没有下载）

**Comment by ikexing-cn** [comment]
开始的时候用第二条线路

**Comment by YuHuai-Golden** [comment]
您好，我尝试了后还是没有成功播放
对于“使用第二条线路的理解”：
我在录入后直接使用第二个
和我切换直播间的线路，到线路二后抓取流
两种方法都没有成功
ps：再次感谢您的帮助

**Comment by ikexing-cn** [comment]
![图片](https://user-images.githubusercontent.com/75018198/168424334-d066afb1-47f0-44e5-aaf3-6f18d6f72a2c.png)

----

选v2api

**Comment by XIYU11864** [comment]
直播间号33还是不能获取流

**Comment by XIYU11864** [comment]
卡在选清晰度

**Comment by ikexing-cn** [comment]
https://github.com/hLdont/bilibili-live-stream-forWin
试试这个吧，确实有bug，但是我现在没法修。

**Comment by ikexing-cn** [comment]
已经修复,请下载0.0.4版本
